version: "3.9"

services:

  nginx:
    container_name: nginx
    image: nginx:1.24
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./resources/static:/opt/jirarush/resources/static:ro
    depends_on:
      - jira
    restart: always

  jira:
    image: jira-prod-img
    container_name: jira-prod
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USERNAME: jira
      DB_PASSWORD: JiraRush
      GITHUB_CLIENT_ID: 3d0d8738e65881fff266
      GITHUB_CLIENT_SECRET: 0f97031ce6178b7dfb67a6af587f37e222a16120
      GOOGLE_CLIENT_ID: 329113642700-f8if6pu68j2repq3ef6umd5jgiliup60.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      GITLAB_CLIENT_ID: b8520a3266089063c0d8261cce36971defa513f5ffd9f9b7a3d16728fc83a494
      GITLAB_CLIENT_SECRET: e72c65320cf9d6495984a37b0f9cc03ec46be0bb6f071feaebbfe75168117004
      MAIL_USERNAME: jira4jr@gmail.com
      MAIL_PASSWORD: zdfzsrqvgimldzyj
    expose:
      - "8080"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15.2
    container_name: jira-postgres-db
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: JiraRush
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always
